package com.imc.vms_backend.email;

public enum EmailType {
    VENDOR_APPROVED,
    VENDOR_REJECTED,
    INVOICE_CREATOR_APPROVED,
    INVOICE_VERIFIER_APPROVED,
    INVOICE_REJECTED,
    INVOICE_APPROVED,
    INVOICE_PAID,
    VENDOR_CREDENTIALS_RESET
}
